In [1]:
# Vizuelna podešavanja okruženja (samo razvuče notebook na širinu ekrana)
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

In [13]:
#ucitavanje ruti
import pandas as pd

dataRoutesPath = "data/routes.csv"
dataStopsPath = 'data/stops.csv'
dataTripsPath= 'data/trips.csv'
dataStopTimesPath= 'data/stop_times.csv'
dataDayRoutesPath='data/day_routes.csv'
dataStops=pd.read_csv(dataStopsPath)
dataRoutes = pd.read_csv(dataRoutesPath) 
dataTrips=pd.read_csv(dataTripsPath)
dataStopTimes=pd.read_csv(dataStopTimesPath,low_memory=False)
dataDayRoutes=pd.read_csv(dataDayRoutesPath)
print(dataDayRoutes)
#print(dataStopTimes)
#print(dataStops)
#print(dataRoutes)
#print(dataTrips)

     route_id  agency_id route_short_name  \
0           2          1                2
1           5          1                5
2           6          1                6
3           7          1                7
4           9          1                9
5          10          1               10
6          11          1               11
7          12          1               12
8          14          1               14
9          15          1               15
..        ...        ...              ...
163     10706          1             706E
164     20022          1              22L
165     20026          1              26L
166     20060          1              60L
167     20406          1             406L
168     20407          1             407L
169     20505          1             505R
170     20703          1            703L1
171     40101          1             EKO1
172     40102          1             EKO2

                                       route_long_name  route_desc  \
0                    Unutrašnji Krug - Spoljašnji Krug         NaN
1                  Kalemegdan /Donji Grad/ - Ustanička         NaN
2                                Tašmajdan - Ustanička         NaN
3                                  Ustanička - Blok 45         NaN
4                                    Banjica - Blok 45         NaN
5                   Kalemegdan /Donji Grad/ - Banjica          NaN
6                    Kalemegdan /Donji Grad/ - Blok 45         NaN
7                     Omladinski Stadion - Banovo Brdo         NaN
8                                  Ustanička - Banjica         NaN
9                     Zeleni Venac - Zemun /Novi Grad/         NaN
..                                                 ...         ...
163       Zemun /Kej Oslobođenja/ - Aerodrom Batajnica         NaN
164                       Studentski Trg - Trg Slavija         NaN
165         Medaković 3 - Vojvode Vlahovića /Terminus/         NaN
166              Zeleni Venac - Novi Beograd /Toplana/         NaN
167  Voždovac  Zemljoradnička - Beli Potok /Igralište/         NaN
168                     Bela Reka - Trebež (Okretnica)         NaN
169                Miljakovac 1  - Miljakovačke Staze          NaN
170  Zemun /Kej Oslobođenja/ - Batajnica /Železničk...         NaN
171                    Vukov Spomenik - Naselje Belvil         NaN
172      Src Milan Gale Muškatirović - Beograd Na Vodi         NaN

     route_type  route_url route_color route_text_color
0             0        NaN      FF0000           FFFFFF
1             0        NaN      FF0000           FFFFFF
2             0        NaN      FF0000           FFFFFF
3             0        NaN      FF0000           FFFFFF
4             0        NaN      FF0000           FFFFFF
5             0        NaN      FF0000           FFFFFF
6             0        NaN      FF0000           FFFFFF
7             0        NaN      FF0000           FFFFFF
8             0        NaN      FF0000           FFFFFF
9             3        NaN      0000FF           FFFFFF
..          ...        ...         ...              ...
163           3        NaN      0000FF           FFFFFF
164         800        NaN      FF8106           FFFFFF
165         702        NaN      008000           FFFFFF
166         702        NaN      008000           FFFFFF
167         702        NaN      008000           FFFFFF
168         702        NaN      008000           FFFFFF
169         702        NaN      008000           FFFFFF
170           3        NaN      0000FF           FFFFFF
171           3        NaN      0000FF           FFFFFF
172           3        NaN      0000FF           FFFFFF

[173 rows x 9 columns]

In [14]:
wantedLabels=['trip_id', 'arrival_time','stop_id','stop_sequence']

dataStopTimes=dataStopTimes[wantedLabels]
dataStopTimes2=dataStopTimes
dataStopTimes=dataStopTimes[(dataStopTimes['stop_sequence']==1) ]

In [15]:
#izbacivanje suvisnih kolona
wantedLabels=['route_id','service_id','trip_id','direction_id']
dataTrips=dataTrips[wantedLabels]
print(dataTrips)

       route_id        service_id  trip_id  direction_id
0             2     Zimski-Subota  1421378             0
1             2     Zimski-Subota  1421379             0
2             2     Zimski-Subota  1421380             0
3             2     Zimski-Subota  1421381             0
4             2     Zimski-Subota  1421382             0
5             2     Zimski-Subota  1421383             0
6             2     Zimski-Subota  1421384             0
7             2     Zimski-Subota  1421385             0
8             2     Zimski-Subota  1421386             0
9             2     Zimski-Subota  1421387             0
...         ...               ...      ...           ...
66043     90004  Zimski-Radni Dan  1400703             1
66044     90004  Zimski-Radni Dan  1400704             1
66045     90004  Zimski-Radni Dan  1400705             1
66046     90004  Zimski-Radni Dan  1400706             1
66047     90004  Zimski-Radni Dan  1400707             1
66048     90004  Zimski-Radni Dan  1400708             1
66049     90004  Zimski-Radni Dan  1400709             1
66050     90004  Zimski-Radni Dan  1400710             1
66051     90004  Zimski-Radni Dan  1400711             1
66052     90004  Zimski-Radni Dan  1400712             1

[66053 rows x 4 columns]

In [16]:
wantedLabels=['stop_id','stop_name','stop_lat','stop_lon','zone_id']
dataStops=dataStops[wantedLabels]
print(dataStops)

      stop_id                   stop_name   stop_lat   stop_lon  zone_id
0           1     Kalemegdan (Donji Grad)  44.826810  20.453274        1
1           2            Tadeuša Košćuška  44.825917  20.455243        1
2           3            Tadeuša Košćuška  44.826253  20.454967        1
3           4                  Kalemegdan  44.820329  20.453252        1
4           5                  Kalemegdan  44.820884  20.454076        1
5           6                 Pristanište  44.818662  20.449412        1
6           7                 Pristanište  44.818992  20.449515        1
7           8                Brankov Most  44.814955  20.450771        1
8           9                Brankov Most  44.814563  20.451127        1
9          10          Ekonomski Fakultet  44.810884  20.454124        1
...       ...                         ...        ...        ...      ...
3120     7809               Kuzmanovići R  44.621213  20.429443        3
3121     7877           Petkovići - Trafo  44.632915  20.434839        3
3122     7878           Petkovići - Trafo  44.632992  20.435037        3
3123     7879        Petkovići Raskrsnica  44.641568  20.441715        3
3124     7880        Petkovići Raskrsnica  44.641455  20.441587        3
3125     7941                   Simić - R  44.626497  20.429264        3
3126     7942                   Simić - R  44.626713  20.429340        3
3127     7968  Stara Lipovica - Okretnica  44.613962  20.430680        3
3128     7969                    Manastir  44.616600  20.430119        3
3129     7970                    Manastir  44.616217  20.430603        3

[3130 rows x 5 columns]

In [17]:
#provera
print(dataStops['stop_id'].isnull().values.any())
print(dataStops['stop_id'].is_unique)

False
True

In [18]:
wantedLabels=['route_id','route_short_name','route_long_name','route_type']
dataRoutes=dataRoutes[wantedLabels]
dataDayRoutes=dataDayRoutes[wantedLabels]
print(dataRoutes)

     route_id route_short_name                             route_long_name  \
0           2                2           Unutrašnji Krug - Spoljašnji Krug
1           5                5         Kalemegdan /Donji Grad/ - Ustanička
2           6                6                       Tašmajdan - Ustanička
3           7                7                         Ustanička - Blok 45
4           9                9                           Banjica - Blok 45
5          10               10          Kalemegdan /Donji Grad/ - Banjica
6          11               11           Kalemegdan /Donji Grad/ - Blok 45
7          12               12            Omladinski Stadion - Banovo Brdo
8          14               14                         Ustanička - Banjica
9          15               15            Zeleni Venac - Zemun /Novi Grad/
..        ...              ...                                         ...
204     51603            603Na                   Trg Republike - Ugrinovci
205     52047             47Nb   Trg Slavija - Resnik /Železnička Stanica/
206     52101            101Nb                     Trg Republike - Borča 3
207     52304            304Nb                     Trg Republike - Ritopek
208     52511            511Nb               Trg Republike - Novi Železnik
209     53047             47Nv  Miljakovac 2 - Resnik /Železnička Stanica/
210     90001               E1                         Ustanička - Blok 45
211     90002               E2                Petlovo Brdo - Trg Republike
212     90003               E6         Mirijevo 4 - Novi Beograd /Blok 45/
213     90004               E9                   Kumodraž - Studentski Trg

     route_type
0             0
1             0
2             0
3             0
4             0
5             0
6             0
7             0
8             0
9             3
..          ...
204           3
205           3
206           3
207           3
208           3
209           3
210         702
211         702
212         702
213         702

[214 rows x 4 columns]

In [19]:
print(dataRoutes['route_id'].isnull().values.any())
print(dataRoutes['route_id'].is_unique)

False
True

In [20]:
import pickle
with open("data_cleaned/day_routes", 'wb') as file:
    pickle.dump(dataDayRoutes, file)
with open("data_cleaned/routes", 'wb') as file:
    pickle.dump(dataRoutes, file)
with open("data_cleaned/stops", 'wb') as file:
    pickle.dump(dataStops, file)
with open("data_cleaned/trips", 'wb') as file:
    pickle.dump(dataTrips, file)
with open("data_cleaned/stop_times",'wb') as file:
    pickle.dump(dataStopTimes,file)
with open("data_cleaned/stop_times2",'wb') as file:
    pickle.dump(dataStopTimes2,file)

In [21]:
import pickle
with open("data_cleaned/routes", 'rb') as file:
    dataRoutes = pickle.load(file)
with open("data_cleaned/stops", 'rb') as file:
    dataStops = pickle.load(file)
with open("data_cleaned/trips", 'rb') as file:
    dataTrips = pickle.load(file)
with open("data_cleaned/stop_times", 'rb') as file:
    dataStopTimes = pickle.load(file)
with open("data_cleaned/stop_times2", 'rb') as file:
    dataStopTimes2 = pickle.load(file)
print(dataStopTimes2)

         trip_id arrival_time  stop_id  stop_sequence
0         665800     20:00:00      638              1
1         665800     20:01:00      148              2
2         665800     20:02:00      746              3
3         665800     20:04:00      845              4
4         665800     20:06:00      847              5
5         665800     20:07:00      849              6
6         665800     20:09:00      851              7
7         665800     20:10:00      859              8
8         665800     20:11:00      853              9
9         665800     20:14:00      291             10
...          ...          ...      ...            ...
1648771  1494173     23:00:00     2210             15
1648772  1494173     23:01:00     2212             16
1648773  1494173     23:06:00     1283             17
1648774  1494173     23:07:00     1285             18
1648775  1494173     23:09:00     1287             19
1648776  1494173     23:11:00     1289             20
1648777  1494173     23:13:00     1291             21
1648778  1494173     23:14:00     1293             22
1648779  1494173     23:16:00     1295             23
1648780  1494173     23:17:00     1297             24

[1648781 rows x 4 columns]

In [11]:

def mul5(x,y):
        return x*y;

In [12]:
import datetime as time
from operator import mul



def timeToMinutes(x):
  factors = (60, 1, 1/60)
  x = sum(i*j for i, j in zip(map(int, x.split(':')), factors))
  return x

In [15]:
#%pip install python-docx
import docx
import pandas as pd
#Ispis df-ova u dockx
# i am not sure how you are getting your data, but you said it is a
# pandas data frame
def df_toDocx(output,data):
    


    # open an existing document
    doc = docx.Document()

    # add a table to the end and create a reference variable
    # extra row is so we can add the header row
    t = doc.add_table(data.shape[0]+1, data.shape[1])

    # add the header rows.
    for j in range(data.shape[-1]):
        t.cell(0,j).text = data.columns[j]

# add the rest of the data frame
    for i in range(data.shape[0]):
        for j in range(data.shape[-1]):
            t.cell(i+1,j).text = str(data.values[i,j])

# save the doc
    print(doc)
    doc.save(output)

In [16]:
# 2.1
pd.set_option('display.max_rows', None)
pd.set_option('display.min_rows', 50)
#spajanje dataseta stoptimes i trips
import numpy as np
import functools
data=dataStopTimes.merge(dataTrips)
#print(data)
data['number']=0
# Odredjivanje krajnjeg i pocetnog polaska a zatim i broj polasaka kao i prosecno vreme izmedju 2 za svaki od smerova za sve rute ->result
result = data.groupby(['route_id','service_id','direction_id']).agg(
    number=('route_id','size'),
    Min=('arrival_time', 'min'),
    Max=('arrival_time', 'max'))
result.columns=['number','Min','Max']
result['Min']=result['Min'].apply(timeToMinutes)
result['Max']=result['Max'].apply(timeToMinutes)
result['diff']=result['Max']-result['Min']
result['polasci']=result['diff']/result['number']

if 'Min' in result.columns:
    result = result.drop(['Min'], axis=1)
if 'Max' in result.columns:
    result = result.drop(['Max'], axis=1)
if 'diff' in result.columns:
    result= result.drop(['diff'],axis=1)


result=result.reset_index();

#print (result['service_id'])
if 'number' in data.columns:
    data = data.drop(['number'], axis=1)



#Odredjivanje prosecnog vremena polaska usredjnjavanjem po smerovima ->result2

result2=result.groupby(['route_id','service_id']).agg(AVG=('polasci','mean'))

#Izbacivanje ruta sa samo jednim polaskom
mask=result2['AVG']>0
result2=result2[mask]
result2=result2.reset_index();

#Odredjivanje dana kojim odredjene rute operisu
result3 = result2.groupby(['route_id'])['service_id'].apply(','.join).reset_index()





#data=data.merge(result2)
#dodavanje ruta u odrejne skupove u odnosu na to kojim danima operisu
setSva3 = set()
setVikend=set()
setRSubota=set()
setRNedelja=set()
setRadni=set()
setSubota=set()
setNedelja=set()
for i in range(0 ,result3.shape[0]):
    if(('Zimski-Radni Dan' in result3.iloc[i]['service_id']) and ('Zimski-Subota' in result3.iloc[i]['service_id']) and 'Zimski-Nedelja' in result3.iloc[i]['service_id']):
        setSva3.add(result3.iloc[i]['route_id'])
    elif('Zimski-Subota' in result3.iloc[i]['service_id'] and 'Zimski-Nedelja' in result3.iloc[i]['service_id']):
        setVikend.add(result3.iloc[i]['route_id'])
    elif ('Zimski-Radni Dan' in result3.iloc[i]['service_id'] and 'Zimski-Subota' in result3.iloc[i]['service_id']):
        setRSubota.add(result3.iloc[i]['route_id'])
    elif('Zimski-Radni Dan' in result3.iloc[i]['service_id'] and 'Zimski-Nedelja' in result3.iloc[i]['service_id']):
        setRNedelja.add(result3.iloc[i]['route_id'])
    elif("Zimski-Radni Dan" in result3.iloc[i]['service_id']):
        setRadni.add(result3.iloc[i]['route_id'])
    elif ('Zimski-Subota' in result3.iloc[i]['service_id']):
        setSubota.add(result3.iloc[i]['route_id'])
    elif ('Zimski-Nedelja' in result3.iloc[i]['service_id']):
        setNedelja.add(result3.iloc[i]['route_id'])

#print(len(setSva3))
#print(len(setVikend))
#print(len(setRSubota))
#print(len(setRNedelja))
#print(len(setRadni))
#print(len(setSubota))
#print(len(setNedelja))



#izracunavanje prosecnog vremena izmedju polazaka u odnosu na kategoriju gde rute upadaju
for i in setSva3:
    mask=((result2['service_id'] =='Zimski-Radni Dan') & (result2['route_id']==i))
    result2.update(result2[mask]['AVG'].mul(5))
    
for i in setRSubota:
    mask=((result2['service_id'] =='Zimski-Radni Dan') & (result2['route_id']==i))
    mask2=((result2['service_id'] =='Zimski-Subota') & (result2['route_id']==i))
    result2.update(result2[mask]['AVG'].mul(35/6))
    result2.update(result2[mask2]['AVG'].mul(7/6))
for i in setRadni:
     mask=((result2['service_id'] =='Zimski-Radni Dan') & (result2['route_id']==i))
     result2.update(result2[mask]['AVG'].mul(7))
result4= result2.groupby(['route_id'],as_index=False).agg(SUM=('AVG','sum'))
result4.update(result4['SUM'].div(7))
result4=result4.sort_values(by='SUM')
#df.sort_values(by='col1', ascending=False)

result5=result4.merge(dataDayRoutes)[['route_id','route_short_name','SUM']]

display(result5)
df_toDocx('./docks/prosecno_vreme_izmedju_polazaka.docx',result5)

     route_id route_short_name        SUM
0       20022              22L   4.779998
1          26               26   6.037162
2       10029              29A   6.370196
3          41               41   6.605340
4          31               31   6.636673
5         309              309   6.974665
6          95               95   7.295471
7          50               50   7.433217
8          16               16   7.570974
9         511              511   7.769789
10         23               23   7.791103
11         48               48   7.922175
12         15               15   8.091837
13         88               88   8.137913
14         46               46   8.153907
15         37               37   8.196700
16         56               56   8.214666
17         17               17   8.227417
18         45               45   8.375217
19         27               27   8.398619
20      10027              27E   8.533528
21         47               47   8.604464
22         33               33   8.661781
23         43               43   8.830401
24         84               84   8.913382
25         59               59   9.100924
26         18               18   9.157657
27         65               65   9.296472
28         35               35   9.454947
29          7                7   9.561319
30          9                9   9.619126
31         40               40   9.645056
32         94               94  10.056514
33         28               28  10.078539
34      10003               3A  10.777493
35         32               32  10.898886
36      20026              26L  10.941262
37         52               52  10.964750
38      40102             EKO2  11.118132
39         75               75  11.352920
40         39               39  11.467770
41         96               96  11.915642
42         53               53  11.932714
43          5                5  11.978328
44          2                2  12.062981
45         74               74  12.071619
46         25               25  12.106541
47         83               83  12.193737
48         51               51  12.251868
49      10021              21A  12.290910
50        101              101  12.299336
51        601              601  12.562131
52      10013               13  12.657050
53         78               78  12.668617
54         73               73  13.002098
55         12               12  13.150191
56        704              704  13.782152
57         71               71  13.972583
58         79               79  13.988363
59        706              706  13.997701
60         77               77  14.092462
61        308              308  14.096392
62         55               55  14.304473
63         10               10  14.569161
64         89               89  14.594962
65        505              505  14.871795
66      10505             505L  15.176066
67         49               49  15.547508
68         24               24  15.726998
69        307              307  16.219470
70         42               42  16.501457
71      10025              25P  16.569684
72        302              302  16.732516
73        707              707  17.018850
74         58               58  17.185085
75        305              305  17.258739
76         67               67  17.609203
77         82               82  17.869564
78         14               14  18.005051
79         85               85  18.049703
80        611              611  18.274197
81        504              504  19.035088
82        405              405  19.619343
83        105              105  19.652516
84         66               66  19.722222
85      10702             702L  20.213326
86        610              610  20.369479
87        700              700  20.430839
88      10703             703L  20.521779
89        551              551  20.565766
90        502              502  21.428571
91         30               30  21.544928
92         81               81  22.277567
93         36               36  22.307692
94        310              310  22.749608
95        531              531  22.925619
96         44               44  23.106250
97         11               11  23.245169
98      10081              81L  23.584636
99         20               20  23.772757
100         6                6  23.803211
101       402              402  23.810465
102       108              108  23.893468
103       532              532  23.936211
104     40101             EKO1  24.056324
105       311              311  24.166285
106       401              401  24.736846
107     20703            703L1  24.839765
108        57               57  24.994613
109     10309             309L  25.095238
110     10105             105L  25.228880
111       604              604  25.544032
112        70               70  25.667828
113       605              605  25.671518
114        92               92  26.034843
115        34               34  26.127727
116       304              304  26.555641
117        68               68  26.694649
118       202              202  26.873669
119       708              708  27.163038
120        91               91  27.275234
121       603              603  27.414106
122       104              104  28.321793
123       709              709  28.584290
124       312              312  29.000000
125       306              306  29.112376
126       521              521  29.149123
127       512              512  29.484185
128     10038              38L  29.921875
129       533              533  30.387205
130       602              602  31.141112
131        72               72  31.190194
132     10032              32E  31.203704
133       506              506  32.143802
134       534              534  33.042380
135        87               87  33.575218
136       409              409  33.703704
137       507              507  34.596774
138       403              403  35.208333
139     20406             406L  35.234375
140       303              303  36.625677
141        38               38  37.222222
142        64               64  38.181818
143     10087              87A  38.181818
144       606              606  38.688172
145     10405             405L  39.689840
146       513              513  40.716868
147       408              408  41.744479
148       106              106  42.261905
149     20407             407L  42.875000
150       407              407  43.269231
151       711              711  47.916667
152     10056              56L  48.461538
153       613              613  49.642857
154       705              705  50.015528
155       503              503  51.048044
156     20505             505R  51.562500
157        76               76  53.182234
158       612              612  53.857143
159        54               54  55.398352
160       553              553  56.524675
161       501              501  56.833333
162       107              107  57.572368
163       102              102  58.625000
164        60               60  60.750000
165     20060              60L  64.675454
166     10706             706E  65.423469
167       406              406  65.735294
168       404              404  65.882353
169     10035              35L  66.000000
170       110              110  74.333333
171       109              109  76.380952
172       607              607  91.875000

<docx.document.Document object at 0x0000027A5E9DF9C0>

In [17]:
# 2.2
pd.set_option('display.min_rows',20)
pd.set_option('display.max_rows',20)

result = dataStops[['stop_id','stop_name']]

result= result.merge(dataStopTimes2.merge(dataDayRoutes.merge(dataTrips)))

if 'arrival_time' in result.columns:
    result = result.drop(['arrival_time'], axis=1) 
result=result.sort_values(by='stop_id')
result= result.merge(dataTrips)

if 'service_id' in result.columns:
    result = result.drop(['service_id'], axis=1) 
if 'direction_id' in result.columns:
    result = result.drop(['direction_id'], axis=1) 
if 'trip_id' in result.columns:
    result.drop(['trip_id'], axis=1, inplace = True) 

result2 = result.groupby(['stop_id','route_id'],as_index=False).first()


result3=result2
#odredjivanje stajalista sa najvecim brojem linija ->result3
result3 = result3.groupby(['stop_id','stop_name'],as_index=False).agg(count=('stop_name','count'))
result3.reset_index()
result3=result3.sort_values(by='count',ascending=False)
display(result3)

#df_toDocx('./docks/stajaliste_max_linija.docx',result3)
result2.reset_index()

#odredjivanje linija sa najvecim brojem stajalista ->result5
result4['count']=0
result4 = result2.groupby('route_id',as_index=False, sort=False).size()
result4=result4.sort_values(by='size',ascending=False)


result5=result4.merge(dataDayRoutes)
result5=result5[['route_short_name','size']]
display(result5)
#df_toDocx('./docks/linije_max_stajalista.docx',result5)

#print(dataStopTimes)

      stop_id                          stop_name  count
256       298                       Brankov Most     16
461       503                      Ada Ciganlija     16
453       495                              Sajam     16
454       496                              Sajam     16
118       149                    Karađorđev Park     15
117       148                    Karađorđev Park     15
116       147  Trg Slavija /Bulevar Oslobođenja/     14
155       186                           Kijevska     13
153       184                       Dom Zdravlja     13
331       373          Bulevar Maršala Tolbuhina     13
...       ...                                ...    ...
1893     1958                 Umka - Karađorđeva      1
1892     1957                  Blagoja Rankovića      1
1891     1956                     Pećani /Škola/      1
1890     1955                    Surčin /Centar/      1
274       316                             Prilaz      1
1882     1947               V. Moštanica - Crkva      1
1881     1946             V. Moštanica - Ekonom.      1
1879     1944                        Mz Železnik      1
1878     1943                        Mz Železnik      1
3115     7970                           Manastir      1

[3116 rows x 3 columns]

    route_short_name  size
0                25P   104
1                605   103
2                 94    98
3                 74    95
4                610    90
5                 73    84
6                 95    84
7                302    83
8                405    81
9                604    80
..               ...   ...
163             702L    21
164              310    20
165              700    19
166              21A    19
167               38    18
168              533    17
169              87A    16
170              110    14
171               87    14
172              22L    10

[173 rows x 2 columns]

In [19]:
df_toDocx('./docks/stajaliste_max_linija.docx',result3.head(100))
df_toDocx('./docks/linije_max_stajalista.docx',result5)

<docx.document.Document object at 0x0000027A5C087580>
<docx.document.Document object at 0x0000027A5EB29700>

In [11]:
pd.set_option('display.min_rows',20)
pd.set_option('display.max_rows',20)
data=dataStopTimes2.merge(dataTrips)
data2=dataStops[['stop_id','stop_name']]
data=data.merge(dataDayRoutes).merge(data2)
if 'direction_id' in data.columns:
    data = data.drop(['direction_id'], axis=1) 
if 'arrival_time' in data.columns:
    data = data.drop(['arrival_time'], axis=1)    
if 'trip_id' in data.columns:
    data = data.drop(['trip_id'], axis=1)   
    
#print(data)
maskR = data['service_id']=='Zimski-Radni Dan'
maskS= data['service_id']=='Zimski-Subota'
maskN= data['service_id']=='Zimski-Nedelja'
dataR=data[maskR]
dataS=data[maskS]
dataN=data[maskN]

dataR=dataR.groupby(['stop_id','stop_name'],as_index=False, sort=False).size()
dataR=dataR.sort_values(by='size',ascending=False)
display(dataR)
#df_toDocx('./docks/najveci_promet_radni.docx',dataR.head(100))
dataS=dataS.groupby(['stop_id','stop_name'],as_index=False, sort=False).size()
dataS=dataS.sort_values(by='size',ascending=False)
display(dataS)
#df_toDocx('./docks/najveci_promet_subota.docx',dataS.head(100))
dataN=dataN.groupby(['stop_id','stop_name'],as_index=False, sort=False).size()
dataN=dataN.sort_values(by='size',ascending=False)

display(dataN)
#df_toDocx('./docks/najveci_promet_.docx',dataN.head(100))
dataR=dataR.merge(dataStops)

      stop_id                          stop_name  size
518       496                              Sajam  1602
478       495                              Sajam  1574
514       503                      Ada Ciganlija  1572
63        149                    Karađorđev Park  1569
1         148                    Karađorđev Park  1562
309       298                       Brankov Most  1534
64        147  Trg Slavija /Bulevar Oslobođenja/  1366
314       351                  Czk Vlada Divljan  1358
299       350                  Czk Vlada Divljan  1358
517       498                              Ruska  1339
...       ...                                ...   ...
2982     2996                Fudbalsko Igralište    15
2678     1695                     Put Za Dunavac    15
1499     2504                   Moma Stanojlović    14
1502     2503                 Oficirska Kolonija    14
1501     2505                   Moma Stanojlović    14
2679     1732                     Put Za Dunavac    14
1498     2502                 Oficirska Kolonija    14
2470     2847                Novi Beograd (Ušće)    10
3038     3115          Muzej Savremene Umetnosti     7
3039     3116          Muzej Savremene Umetnosti     5

[3116 rows x 3 columns]

      stop_id                          stop_name  size
309       298                       Brankov Most  1257
63        149                    Karađorđev Park  1204
1         148                    Karađorđev Park  1199
518       496                              Sajam  1178
514       503                      Ada Ciganlija  1172
478       495                              Sajam  1168
299       350                  Czk Vlada Divljan  1057
314       351                  Czk Vlada Divljan  1056
64        147  Trg Slavija /Bulevar Oslobođenja/  1051
517       498                              Ruska  1008
...       ...                                ...   ...
2474     1060                                Jrb     9
2475     1063                             Gp Rad     9
3035     3115          Muzej Savremene Umetnosti     9
2468     1053                    Slavka Šlandera     8
2467     1055                        Most Gazela     8
2466     1057               Železnički Most Sava     8
2465     1059               Novi Železnički Most     8
2464     1061                                Jrb     8
2463     1064                             Gp Rad     8
3036     3116          Muzej Savremene Umetnosti     8

[3113 rows x 3 columns]

      stop_id                  stop_name  size
309       298               Brankov Most  1131
518       496                      Sajam  1113
478       495                      Sajam  1099
514       503              Ada Ciganlija  1083
63        149            Karađorđev Park  1034
1         148            Karađorđev Park  1032
517       498                      Ruska   942
314       351          Czk Vlada Divljan   938
299       350          Czk Vlada Divljan   936
511       184               Dom Zdravlja   916
...       ...                        ...   ...
2469     1050             Staro Sajmište     9
3035     3115  Muzej Savremene Umetnosti     9
2472     1056       Železnički Most Sava     9
2463     1064                     Gp Rad     8
3036     3116  Muzej Savremene Umetnosti     8
2468     1053            Slavka Šlandera     8
2467     1055                Most Gazela     8
2466     1057       Železnički Most Sava     8
2465     1059       Novi Železnički Most     8
2464     1061                        Jrb     8

[3113 rows x 3 columns]

In [34]:
df_toDocx('./docks/najveci_promet_radni.docx',dataR.head(100))
df_toDocx('./docks/najveci_promet_subota.docx',dataS.head(100))
df_toDocx('./docks/najveci_promet_.docx',dataN.head(100))

<docx.document.Document object at 0x0000027A5EE47840>
<docx.document.Document object at 0x0000027A5EA02A00>
<docx.document.Document object at 0x0000027A5E4C9540>

In [12]:
#### pd.set_option('display.max_rows',1000)
pd.set_option('display.min_rows',1000)
data=dataStopTimes2.merge(dataTrips)

data=data.merge(dataStops)

data=data[['stop_id','stop_name','route_id']]

#dataRoutes1=dataRoutes[dataRoutes['route_type']==0]
data=data.merge(dataRoutes)


data=data[['stop_id','stop_name','route_type']]

data.sort_values(by='route_type')

data2=data


#print(data)
#data['route_type']=data["route_type"].values.astype(str)
#data=data.groupby(['stop_id','stop_name','route_type'])
#data=data.groupby(['stop_id','stop_name'])['route_type'].apply(','.join).reset_index()
#print(data2)
#print(data)                                  
#result2.groupby(['route_id'])['service_id'].apply(','.join).reset_index()
data3=data.groupby(['stop_id','stop_name','route_type']).first()
#display(data3)
data3=data.reset_index()
data=data.groupby(['stop_id','stop_name']).agg(types=('route_type',pd.Series.nunique))
data=data.reset_index()
#display(data)

#display(data)
#data=data.sort_values(by='types')
data['tip']=''

#print(data)
#print(data.groupby(['types']).size())

for i in range(0 ,data.shape[0]):
    
    if((data.iloc[i]['types'])>1 ):
         data.at[i,'tip']='mesovita'
    else: 
        stop=data3[data3['stop_id']==data.iloc[i]['stop_id']]
      
       # print(stop)
    
        if (3 in stop['route_type'].values or 702 in stop['route_type'].values):
            data.at[i,'tip']='autobuska'
    
        elif (0 in stop['route_type'].values):
            
            data.at[i,'tip']='tramvajska'
         
        elif (800 in stop['route_type'].values):
            data.at[i,'tip']='trolejbuska'

mask=data['types']>1
data[mask]=data[mask].assign(tip='mesovita')

dataStopsExtra=data.merge(dataR)
#display(dataStopsExtra)
with open("data_cleaned/dataStopsExtra", 'wb') as file:
    pickle.dump(dataStopsExtra, file)
#display(data.merge(dataR))
data=data.groupby('tip',as_index=False).size()
display(data)

           tip  size
0    autobuska  2441
1     mesovita   611
2   tramvajska    74
3  trolejbuska     4